# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-24 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodsvisitcount'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='更新时间')),
                ('score', models.CharField(max_length=20, verbose_name='来源')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='是否匿名')),
                ('comment', models.CharField(max_length=1500, verbose_name='评价')),
                ('username', models.CharField(default='null', max_length=1500, verbose_name='名字')),
                ('order', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='CommentOrder', to='orders.OrderInfo', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='goods.SKU', verbose_name='sku')),
            ],
            options={
                'verbose_name': 'SKU评价',
                'verbose_name_plural': 'SKU评价',
                'db_table': 'tb_sku_commnet',
            },
        ),
    ]
